name: Publish assets

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_PUBLISH_ASSETS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_PUBLISH_ASSETS_KEY }}
          aws-region: ${{ secrets.AWS_S3_PUBLISH_ASSETS_REGION }}
      - name: Publish assets
        run: aws s3 sync assets s3://${{ secrets.AWS_S3_PUBLISH_ASSETS_BUCKET }} --delete
